### PR TITLE
First start on a JSON API implementation

### PR DESCRIPTION
**Pull request by dynamiccast**
HI,

I am using Ember.js as a frontend and realized it was not easy to interface with Sails.js since they changed their default adapter in favor of JSON API.
Even though this project looks quit inactive, I still find it is difficult to work with JSON API (and thus Ember) and Sails.js.

Here is a blueprint implementation of JSON API for Sails.js. This is a first start as it only supports basic operations. There is still no support for links, watchers, inclusions nor relationships and still suffer from very little error handling.

I updated the README to detail the installation process.
I would be glad to receive feedback on this as this is one of my first node.js contribution.

You will find a dummy app with tests to validate it is working.

### CODE REVIEW

**Comment by mphasize** [comment]
Hi @dynamiccast, this looks like an awesome start for the json-api and I think it would make a great addition! Unfortunately I'm no longer actively maintaining this repository – I'd recommend you to fork it and continue there and I will update this repo with a link if you want.

**Comment by dynamiccast** [comment]
Hi, Thank you for your response.
I'll do that and let you know.

**Comment by dynamiccast** [comment]
Hi,

Just a few word. I haven't found much time to work on this lately.
However, for those passing by and interested to have Ember and Sails working together with the JSON API adapter, I participated to a Hackathon last week and had the occasion to work with Sails and Ember.
Here is the source code: https://github.com/dynamiccast/greenhub-hackathon-valtech. It uses the code from this pull request to have Sails.js working out of the box with Ember.

**Comment by dynamiccast** [comment]
Hi ! I took the time to make it a real sails hook for everyone to use. It's available at https://github.com/dynamiccast/sails-json-api-blueprints and already on npm under the name `sails-json-api-blueprints`.

It basically contains this PR but packaged as a sails hook. So the only thing one has to do to have a JSON API is to install it with npm : `npm install sails-json-api-blueprints`.

I will work on more feature to hopefully cover all the specs of JSON API.

**Pull request closed without merging**
