### PR TITLE
Advanced

### PR DESCRIPTION
**Pull request by wayne-o**
Fixes casing on some of the linked resources

### CODE REVIEW

**Comment by mphasize** [comment]
@wayne-o I have to think it through, but I wonder why you would actually need to link the "hasOne" relationship? (I.e. why create `links` for a belongsTo model relationship?)

As far as I know, a hasOne association saves the ID of the associated record directly on the primary record, without any further performance penalties for lookups (compared to hasMany). So in my thinking it wouldn't make sense to `link` this associaton, as we can simply include the ID in the response.

On the example you made on the other thread, I would have expected

``` javascript
{
    "listingEvents": [
        {
            // ...
            "location": "ID",
            // ...
        }
    ]
}
```

**Comment by wayne-o** [comment]
I think the issue is that it behaves one way in one instance and another else where

Using links seems to keep ember happy :)

**Comment by wayne-o** [comment]
hmmm - you're right - this doesn't work as expected :/

i'll see why ember wasn't loading the record by it's ID

**Comment by mphasize** [comment]
@wayne-o Since #21 should be solved now and creating `links` for belongsTo / hasOne associations is something I would really advise against, I'll close this PR for the moment. If you think we should reconsider this, feel free to reopen the PR or drop me a note.

Thanks for spotting the bug and investigating it! I really appreciate the work.

**Comment by wayne-o** [comment]
:+1:  

really enjoy working with this stuff - anything i can do to help

**Pull request closed without merging**
