### PR TITLE
Upgraded to lodash 3.x syntax, requiring used modules directly.

### PR DESCRIPTION
**Pull request by Globegitter**
Having worked quite a bit now with lodash in cli tools I could see that it costs quite a bit loading the whole lodash. Not so much an issue on the server, but still doesn't hurt I would say :)

### CODE REVIEW

**Comment by mphasize** [comment]
Since you're looking at the dependencies, do you think it would be possible to require them directly from the generator? 
Define the dependencies in the package.json of our generator project and include them from there, so that developers don't have to setup the _lodash_ and _pluralize_ dependencies anymore?

**Comment by Globegitter** [comment]
Yeah, do you know off the top of your head if I would I into the `bin/index`? But taking a look into the documentation myself now.

**Comment by Globegitter** [comment]
Oohhh you mean just get the path to lodash within the `sails-generate-ember-blueprints` folder?

**Comment by mphasize** [comment]
Yep.

**Comment by Globegitter** [comment]
Not sure of a proper solution really. You could do something like `require('node_modules/sails-generate-ember-blueprints/node_modules/lodash')`, but I am not sure if that always works. What if you do `npm dedupe`? (which flattens your node_modules folder structure as much as possible and could therefore move lodash)

**Comment by Globegitter** [comment]
Hmmm, we could use http://node-machine.org/machinepack-npm/install-package though and then move `lodash` and `pluralize` to devDependencies.

**Comment by mphasize** [comment]
The machinepack is a pretty heavy dependency... mhm... I am undecided on that one.

By the way: If we cannot get the dependencies from this package, there's no real need to actually include them as dependencies.

**Comment by Globegitter** [comment]
I wonder if Sails has a native method. That would be the best solution.

**Comment by mphasize** [comment]
Wait... I just remembered that somebody (maybe even you?) suggested that instead of copying the complete blueprints over, we could just copy shallow blueprints into the actual /api folder that don't do anything except:
`module.exports = require('sails-generate-ember-blueprints/templates/ .... );` 

With that construction we should have access to the dependencies from this project within the blueprints.

**Comment by Globegitter** [comment]
@sgress454 @mikermcneil Do sails generators have an API way to define project dependencies which get installed automatically? Ember-cli provides this feature via `addPackagesToProject()`, see https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L762

**Comment by Globegitter** [comment]
Actually @mphasize that would work as well. and would be quite nice because then you can update project easier - though on the flipside you can't modify as easy. 

I really like this idea, but wonder what the better approach is.

**Comment by mphasize** [comment]
Modifying the blueprints is a very tricky business anyway, since the next update would either destroy your changes or create a need for a complicated compare and merge. (Which reminds me, that I should check if Sails 0.11 brought any significant updates to the blueprints that should be incorporated here...). So ideally I would try to provide config and hooks to customize the blueprints without changing the code...

Plus, if you really need to modify, you could still copy over the blueprints yourself and start hacking...

**Comment by mphasize** [comment]
@Globegitter Is this ready to be merged?

**Comment by Globegitter** [comment]
Yep, have it in my current project and working well.

**Comment by mphasize** [comment]
Tried it and looks good. What do you think in terms of version bump, is this a minor version or a patch?

**Comment by Globegitter** [comment]
Good question, but since upgrading lodash to 3.x can bring potentially breaking changes in a project I would go for `0.1.0`.

**Comment by Globegitter** [comment]
Maybe we can also get the camelCase fixes in. Will make a PR in a bit.

**Comment by mphasize** [comment]
In the advanced branch I added a `emberizeModelIdentity` function in the Ember service to do that. That way it's pretty accessible throughout the code.

**Comment by Globegitter** [comment]
Awesome. Have you also seen my mentions about the sideloaded camelCasing in the other PR? Which is a bit harder to do.

**Comment by mphasize** [comment]
Yes, which made me realize that I hadn't been very thorough when adding the fix. More work needed. ;-)

**Pull request merged**
