### PR TITLE
Update actionUtil.js to support camelCase when receiving values from emb...

### PR DESCRIPTION
**Pull request by alexjp**
...er data json

ember data sends firstwordSecondword, but blueprint was searching for values in firstwordsecondword.

Fixed using code from @globegitter for emberizeJSON to support camelcase

### CODE REVIEW

**Comment by Globegitter** [comment]
Thanks for that @alexjp Could you maybe extract it out into its own `camelCase` function, since it is now being used twice. Doesn't matter if you stick it at the top or end of the file.

**Comment by alexjp** [comment]
yeah, will do it tomorrow and do another pull request

**Comment by Globegitter** [comment]
Is this also fixing sideloaded elements? I am getting back for example `researchprojectactivities`, but ember expects `researchProjectActivities`.

**Comment by alexjp** [comment]
@Globegitter dunno about sideloaded elements, i will have a look at it.
Sorry for not doing it the day i said i would. I have some time to work on this today :) and will take a look at sideloaded elements.

**Comment by Globegitter** [comment]
I found a workaround for sideloaded elements:
https://github.com/mphasize/sails-generate-ember-blueprints/blob/master/templates/api/blueprints/_util/actionUtil.js#L48

needs to use `toCamelCase(sails.models[assoc.collection].globalId)` / `toCamelCase(sails.models[assoc.model].globalId)`

**Comment by Globegitter** [comment]
Just opened https://github.com/balderdashy/sails/issues/2679 for that issue @mphasize. Maybe you know a better way, otherwise we can use the global sails object for now.

**Comment by alexjp** [comment]
@Globegitter thanks, i was doing something similar and confirmed that sideload was not working.

I submitted a pull request for some fixes in that code : https://github.com/mphasize/sails-generate-ember-blueprints/pull/11

Sideload seems to be working now with camelcase.

Thanks !

**Pull request closed without merging**
